project:
  type: book

book:
  title: "Fake Accounts Instagram"
  author: "Antonio Ca√±ete Baena"
  date: "05/24/24"
  chapters:
    - index.qmd
    - analisisExploratorio.qmd
    - visualizacionDatos.qmd
    - reglasAsociacion.qmd
    - fca.qmd
    - regresion.qmd
    - seriesTemporales.qmd
    - otrasTecnicas.qmd
    - demo.qmd
    - summary.qmd
    - references.qmd
# bibliography: references.bib
  
format:
 html:
   theme:
     light: simplex
     dark: superhero
   mainfont: Tahoma
 pdf:
   documentclass: scrreprt

editor: visual

execute:
  freeze: auto